// Generated from /pastry-2.1/src/rice/p2p/past/testing/RawPastRegrTest.java
#include <rice/p2p/past/testing/RawPastRegrTest_testVersionControl_5_receive_5_1_receive_5_1_1_receive_5_1_1_1_receive_5_1_1_1_1_receive_5_1_1_1_1_1.hpp>

#include <java/lang/Object.hpp>
#include <java/lang/String.hpp>
#include <rice/p2p/past/PastContent.hpp>
#include <rice/p2p/past/testing/RawPastRegrTest_testVersionControl_5_receive_5_1.hpp>
#include <rice/p2p/past/testing/RawPastRegrTest_testVersionControl_5_receive_5_1_receive_5_1_1.hpp>
#include <rice/p2p/past/testing/RawPastRegrTest_testVersionControl_5_receive_5_1_receive_5_1_1_receive_5_1_1_1.hpp>
#include <rice/p2p/past/testing/RawPastRegrTest_testVersionControl_5_receive_5_1_receive_5_1_1_receive_5_1_1_1_receive_5_1_1_1_1.hpp>
#include <rice/p2p/past/testing/RawPastRegrTest_testVersionControl_5.hpp>
#include <rice/p2p/past/testing/RawPastRegrTest.hpp>

rice::p2p::past::testing::RawPastRegrTest_testVersionControl_5_receive_5_1_receive_5_1_1_receive_5_1_1_1_receive_5_1_1_1_1_receive_5_1_1_1_1_1::RawPastRegrTest_testVersionControl_5_receive_5_1_receive_5_1_1_receive_5_1_1_1_receive_5_1_1_1_1_receive_5_1_1_1_1_1(RawPastRegrTest_testVersionControl_5_receive_5_1_receive_5_1_1_receive_5_1_1_1_receive_5_1_1_1_1 *RawPastRegrTest_testVersionControl_5_receive_5_1_receive_5_1_1_receive_5_1_1_1_receive_5_1_1_1_1_this, ::rice::p2p::past::PastContent* newFile)
    : super(RawPastRegrTest_testVersionControl_5_receive_5_1_receive_5_1_1_receive_5_1_1_1_receive_5_1_1_1_1_this->RawPastRegrTest_testVersionControl_5_receive_5_1_receive_5_1_1_receive_5_1_1_1_this->RawPastRegrTest_testVersionControl_5_receive_5_1_receive_5_1_1_this->RawPastRegrTest_testVersionControl_5_receive_5_1_this->RawPastRegrTest_testVersionControl_5_this->RawPastRegrTest_this, *static_cast< ::default_init_tag* >(0))
    , RawPastRegrTest_testVersionControl_5_receive_5_1_receive_5_1_1_receive_5_1_1_1_receive_5_1_1_1_1_this(RawPastRegrTest_testVersionControl_5_receive_5_1_receive_5_1_1_receive_5_1_1_1_receive_5_1_1_1_1_this)
    , newFile(newFile)
{
    clinit();
    ctor();
}

void rice::p2p::past::testing::RawPastRegrTest_testVersionControl_5_receive_5_1_receive_5_1_1_receive_5_1_1_1_receive_5_1_1_1_1_receive_5_1_1_1_1_1::receive(::java::lang::Object* result) /* throws(Exception) */
{
    RawPastRegrTest_testVersionControl_5_receive_5_1_receive_5_1_1_receive_5_1_1_1_receive_5_1_1_1_1_this->RawPastRegrTest_testVersionControl_5_receive_5_1_receive_5_1_1_receive_5_1_1_1_this->RawPastRegrTest_testVersionControl_5_receive_5_1_receive_5_1_1_this->RawPastRegrTest_testVersionControl_5_receive_5_1_this->RawPastRegrTest_testVersionControl_5_this->RawPastRegrTest_this->assertTrue(u"Non-Overwriting file should not be null"_j, result != nullptr);
    RawPastRegrTest_testVersionControl_5_receive_5_1_receive_5_1_1_receive_5_1_1_1_receive_5_1_1_1_1_this->RawPastRegrTest_testVersionControl_5_receive_5_1_receive_5_1_1_receive_5_1_1_1_this->RawPastRegrTest_testVersionControl_5_receive_5_1_receive_5_1_1_this->RawPastRegrTest_testVersionControl_5_receive_5_1_this->RawPastRegrTest_testVersionControl_5_this->RawPastRegrTest_this->assertEquals(u"Lookup of non-overwriting file should be correct (second) version"_j, newFile, result);
    RawPastRegrTest_testVersionControl_5_receive_5_1_receive_5_1_1_receive_5_1_1_1_receive_5_1_1_1_1_this->RawPastRegrTest_testVersionControl_5_receive_5_1_receive_5_1_1_receive_5_1_1_1_this->RawPastRegrTest_testVersionControl_5_receive_5_1_receive_5_1_1_this->RawPastRegrTest_testVersionControl_5_receive_5_1_this->RawPastRegrTest_testVersionControl_5_this->RawPastRegrTest_this->stepDone();
    RawPastRegrTest_testVersionControl_5_receive_5_1_receive_5_1_1_receive_5_1_1_1_receive_5_1_1_1_1_this->RawPastRegrTest_testVersionControl_5_receive_5_1_receive_5_1_1_receive_5_1_1_1_this->RawPastRegrTest_testVersionControl_5_receive_5_1_receive_5_1_1_this->RawPastRegrTest_testVersionControl_5_receive_5_1_this->RawPastRegrTest_testVersionControl_5_this->RawPastRegrTest_this->sectionDone();
    RawPastRegrTest_testVersionControl_5_receive_5_1_receive_5_1_1_receive_5_1_1_1_receive_5_1_1_1_1_this->RawPastRegrTest_testVersionControl_5_receive_5_1_receive_5_1_1_receive_5_1_1_1_this->RawPastRegrTest_testVersionControl_5_receive_5_1_receive_5_1_1_this->RawPastRegrTest_testVersionControl_5_receive_5_1_this->RawPastRegrTest_testVersionControl_5_this->RawPastRegrTest_this->testFetch();
}

extern java::lang::Class *class_(const char16_t *c, int n);

java::lang::Class* rice::p2p::past::testing::RawPastRegrTest_testVersionControl_5_receive_5_1_receive_5_1_1_receive_5_1_1_1_receive_5_1_1_1_1_receive_5_1_1_1_1_1::class_()
{
    static ::java::lang::Class* c = ::class_(u"", 0);
    return c;
}

java::lang::Class* rice::p2p::past::testing::RawPastRegrTest_testVersionControl_5_receive_5_1_receive_5_1_1_receive_5_1_1_1_receive_5_1_1_1_1_receive_5_1_1_1_1_1::getClass0()
{
    return class_();
}

