// Forward declarations for java.io
#pragma once


namespace java
{
    namespace io
    {
        class BufferedInputStream;
        class BufferedOutputStream;
        class BufferedReader;
        class BufferedWriter;
        class ByteArrayInputStream;
        class ByteArrayOutputStream;
        struct Closeable;
        class Console;
        struct DataInput;
        class DataInputStream;
        struct DataOutput;
        class DataOutputStream;
        class EOFException;
        struct Externalizable;
        class File;
        class FileDescriptor;
        struct FileFilter;
        class FileInputStream;
        class FileNotFoundException;
        class FileOutputStream;
        class FileReader;
        class FileSystem;
        class File_PathStatus;
        class File_TempDirectory;
        struct FilenameFilter;
        class FilterInputStream;
        class FilterOutputStream;
        struct Flushable;
        class IOException;
        class InputStream;
        class InputStreamReader;
        class InterruptedIOException;
        class InvalidObjectException;
        class NotActiveException;
        class NotSerializableException;
        struct ObjectInput;
        class ObjectInputStream;
        class ObjectInputStream_BlockDataInputStream;
        class ObjectInputStream_Caches;
        class ObjectInputStream_GetField;
        class ObjectInputStream_GetFieldImpl;
        class ObjectInputStream_HandleTable;
        class ObjectInputStream_HandleTable_HandleList;
        class ObjectInputStream_PeekInputStream;
        class ObjectInputStream_ValidationList;
        class ObjectInputStream_ValidationList_Callback;
        struct ObjectInputValidation;
        struct ObjectOutput;
        class ObjectOutputStream;
        class ObjectOutputStream_BlockDataOutputStream;
        class ObjectOutputStream_Caches;
        class ObjectOutputStream_DebugTraceInfoStack;
        class ObjectOutputStream_HandleTable;
        class ObjectOutputStream_PutField;
        class ObjectOutputStream_PutFieldImpl;
        class ObjectOutputStream_ReplaceTable;
        class ObjectStreamClass;
        struct ObjectStreamConstants;
        class ObjectStreamException;
        class ObjectStreamField;
        class OutputStream;
        class OutputStreamWriter;
        class PrintStream;
        class PrintWriter;
        class RandomAccessFile;
        class Reader;
        class SerialCallbackContext;
        struct Serializable;
        class SerializablePermission;
        class StreamCorruptedException;
        class StringReader;
        class UnsupportedEncodingException;
        class Writer;
    } // io
} // java
